#pragma region Apache License 2.0
/*
Nuclex Native Framework
Copyright (C) 2002-2024 Markus Ewald / Nuclex Development Labs

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
#pragma endregion // Apache License 2.0

#ifndef NUCLEX_THINORM_FLUENT_COLUMNINFO_H
#define NUCLEX_THINORM_FLUENT_COLUMNINFO_H

#include "Nuclex/ThinOrm/Config.h"
#include "Nuclex/ThinOrm/Fluent/EntityMappingConfigurator.h"

#include <string> // for std::u8string

namespace Nuclex::ThinOrm::Fluent {

  // ------------------------------------------------------------------------------------------- //

  /// <summary>Describes a table column that has been mapped to an entity attribute</summary>
  class ColumnInfo {

    /// <summary>Initializes a new mapped column description</summary>
    /// <param name="name">Name of the column in the database</param>
    /// <param name="type">RTTI type information for the attribute in the entity class</param>
    /// <param name="getter">Function that reads the column as a <see cref="Value /></param>
    /// <param name="setter">Function that sets the column from a <see cref="Value /></param>
    public: ColumnInfo(
      const std::u8string name,
      const std::type_info &type,
      EntityMappingConfigurator::GetAttributeValueFunction *getter,
      EntityMappingConfigurator::SetAttributeValueFunction *setter
    );

    /// <summary>Name of the column in the database</summary>
    public: std::u8string Name;
    /// <summary>Data type of the column's attribute in the entity class</summary>
    public: const std::type_info &Type;
    /// <summary>Getter function that reads the column as a <see cref="Value" /></summary>
    public: EntityMappingConfigurator::GetAttributeValueFunction *Getter;
    /// <summary>Setter function that sets the column from a <see cref="Value" /></summary>
    public: EntityMappingConfigurator::SetAttributeValueFunction *Setter;

    /// <summary>Whether this column's value is auto-generated by the database</summary>
    public: bool IsAutogenerated;
    /// <summary>Whether this column is the primary key or is part thereof</summary>
    public: bool IsPrimaryKey;
    /// <summary>Whether this column can be set to NULL (omitted value)</summary>
    public: bool IsNullable;

  };

  // ------------------------------------------------------------------------------------------- //

} // namespace Nuclex::ThinOrm::Fluent

#endif // NUCLEX_THINORM_FLUENT_COLUMNINFO_H
