#pragma region Apache License 2.0
/*
Nuclex Native Framework
Copyright (C) 2002-2024 Markus Ewald / Nuclex Development Labs

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
#pragma endregion // Apache License 2.0

// If the library is compiled as a DLL, this ensures symbols are exported
#define NUCLEX_THINORM_SOURCE 1

#include "Nuclex/ThinOrm/Fluent/GlobalEntityRegistry.h"
#include "./GlobalEntityRegistry.Implementation.h"

namespace {

  // ------------------------------------------------------------------------------------------- //
  // ------------------------------------------------------------------------------------------- //

} // anonymous namespace

namespace Nuclex::ThinOrm::Fluent {

  // ------------------------------------------------------------------------------------------- //

  GlobalEntityRegistry::GlobalEntityRegistry() :
    implementation(std::make_unique<Implementation>()) {}

  // ------------------------------------------------------------------------------------------- //

  GlobalEntityRegistry::~GlobalEntityRegistry() = default;

  // ------------------------------------------------------------------------------------------- //

  void GlobalEntityRegistry::AddEntity(
    const std::type_info &entityType, const std::u8string_view &tableName
  ) {

  }

  // ------------------------------------------------------------------------------------------- //

  void GlobalEntityRegistry::AddEntityAttribute(
    const std::type_info &entityType,
    const std::u8string_view &columnName,
    GetAttributeValueFunction *getter,
    SetAttributeValueFunction *setter
  ) {

  }

  // ------------------------------------------------------------------------------------------- //

  void GlobalEntityRegistry::SetColumnNullable(
    const std::type_info &entityType,
    const std::u8string_view &columnName,
    bool isNullable /* = true */
  ) {

  }

  // ------------------------------------------------------------------------------------------- //

  void GlobalEntityRegistry::SetColumnIsPrimaryKey(
    const std::type_info &entityType,
    const std::u8string_view &columnName,
    bool isPrimaryKey /* = true */
  ) {

  }

  // ------------------------------------------------------------------------------------------- //

  void GlobalEntityRegistry::SetColumnIsAutoGenerated(
    const std::type_info &entityType,
    const std::u8string_view &columnName,
    bool isAutoGenerated /* = true */
  ) {

  }

  // ------------------------------------------------------------------------------------------- //

} // namespace Nuclex::ThinOrm::Fluent
